# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mNeme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mNeme
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'SOTabBar'
pod 'GoogleSignIn'
pod 'FacebookLogin'
pod 'FacebookCore'
pod 'TaggerKit'
  target 'mNemeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mNemeUITests' do
    # Pods for testing
  end

end
